# Generated by Django 3.1.7 on 2021-03-15 19:41

import cs111.django.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=cs111.django.storages.OverwriteFileSystemStorage, upload_to='cs111')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.SmallIntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('version', models.CharField(max_length=255)),
                ('pdf', models.FileField(storage=cs111.django.storages.OverwriteFileSystemStorage, upload_to='cs111/lectures')),
            ],
        ),
    ]
