# Generated by Django 3.1.7 on 2021-03-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs111', '0003_add_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='youtube',
            field=models.URLField(blank=True),
        ),
    ]
