# Generated by Django 3.1.7 on 2021-04-06 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs111', '0004_add_youtube'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='youtube2',
            field=models.URLField(blank=True),
        ),
    ]
