# Generated by Django 3.1.7 on 2021-06-11 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs111', '0007_add_midterm_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalExamGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.FloatField()),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_grade', to='cs111.role')),
            ],
        ),
    ]
