# Generated by Django 3.1.7 on 2021-06-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs111', '0010_add_offering'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ucla_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
