# Generated by Django 3.2.5 on 2021-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs111', '0011_add_ucla_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
