# Generated by Django 3.2.7 on 2021-09-20 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs111', '0012_add_lab_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegrade',
            name='offering',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='cs111.offering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evaluationgrade',
            name='offering',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_grades', to='cs111.offering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='finalexamgrade',
            name='offering',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_grades', to='cs111.offering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labgrade',
            name='offering',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='lab_grades', to='cs111.offering'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='midtermgrade',
            name='offering',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='midterm_grades', to='cs111.offering'),
            preserve_default=False,
        ),
    ]
