# Generated by Django 3.2.7 on 2021-09-29 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_gitolite', '0001_initial'),
        ('cs111', '0013_add_offering_to_grades'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpstreamStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_merged', models.BooleanField()),
                ('repo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_status', to='django_gitolite.repo')),
            ],
        ),
        migrations.CreateModel(
            name='SubmissionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_modified', models.BooleanField()),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_statuses', to='cs111.lab')),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_statuses', to='django_gitolite.repo')),
            ],
            options={
                'unique_together': {('repo', 'lab')},
            },
        ),
    ]
