# Generated by Django 3.2.7 on 2021-10-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs111', '0014_add_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(choices=[('I', 'Instructor'), ('T', 'TA'), ('S', 'Student'), ('A', 'Audit')], max_length=1),
        ),
    ]
