# Generated by Django 3.2.7 on 2021-12-09 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cs111', '0015_add_audit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_grades', to='cs111.role'),
        ),
        migrations.AlterField(
            model_name='evaluationgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_grades', to='cs111.role'),
        ),
        migrations.AlterField(
            model_name='finalexamgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_exam_grades', to='cs111.role'),
        ),
        migrations.AlterField(
            model_name='midtermgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='midterm_grades', to='cs111.role'),
        ),
        migrations.AlterUniqueTogether(
            name='coursegrade',
            unique_together={('offering', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='evaluationgrade',
            unique_together={('offering', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='finalexamgrade',
            unique_together={('offering', 'student')},
        ),
        migrations.AlterUniqueTogether(
            name='labgrade',
            unique_together={('offering', 'student', 'lab')},
        ),
        migrations.AlterUniqueTogether(
            name='midtermgrade',
            unique_together={('offering', 'student')},
        ),
    ]
