$clean_ext = 'bbl exitCode png run.xml sh stderr stdout synctex';
$pdf_mode = 5;
$postscript_mode = $dvi_mode = 0;
$xelatex = 'xelatex -no-pdf -shell-escape -synctex=15 %O %S';
$recorder = 0;

@default_files = ('favicon.tex');
